name: Test & Lint
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: abatilo/actions-poetry@v2.1.0
    - name: Install dependencies
      run: |
        poetry install
    - name: pytest
      run: |
        poetry run pytest tests
    - name: pylint
      run: |
        poetry run pylint -E dialogs_framework tests
    - name: mypy
      run: |
        poetry run mypy --ignore-missing-imports dialogs_framework tests
    - name: black
      run: |
        poetry run black --check .

