name: Test & Lint
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: abatilo/actions-poetry@v2.1.0
    - name: Install dependencies
      run: |
        poetry install
    - name: Pytest
      run: |
        poetry run pytest tests

